let url = window.location.href;
let title = document.title;
let mnsocial = document.getElementsByClassName('mn-social-bottom');
mnsocial[0].href = 'https://www.facebook.com/sharer/sharer.php?u=' + url;
mnsocial[1].href = 'https://twitter.com/intent/tweet?text=' + 'Olha que legal esse site: ' + title + ' ' + url;
mnsocial[2].href = 'https://www.linkedin.com/cws/share?url=' + url;
mnsocial[3].href = 'mailto:?&subject=' + url + '&body=' + title + ', ' + url;
mnsocial[4].href = 'https://api.whatsapp.com/send?text=' + url;
// mnsocial[5].href = 'http://www.reddit.com/submit?url=' + url;
// mnsocial[6].href = 'https://pinterest.com/pin/create/link/?url=' + url;
